import "@/styles/global.scss";
import "@/styles/reset.scss";
import { ConfigProvider } from "antd";
import { borderColor, font, primary, whiteColor } from "@/utlls/variables";
import RootStyleRegistry from "@/utlls/RootStyleRegistry";
import Header from "@/components/Layout/Header";
import Footer from "@/components/Layout/Footer";
import Loading from "@/components/Layout/Loading";
import { Suspense } from "react";
import { getPages } from "@/utlls/request";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
  metadataBase: new URL("https://declicweb.web.app/"),
  alternates: {
    canonical: "/",
  },
};

export default async function RootLayout({ children }) {
  await new Promise((resolve) => setTimeout(resolve, 3000));
  const pages = await getPages();
  return (
    <html lang="en">
      <link rel="shortcut icon" href="/images/favicon.png" />
      <meta charSet="UTF-8" />
      <meta name="robots" content="index,follow" />
      <meta name="googlebot" content="index,follow" />

      <body>
        <ConfigProvider
          theme={{
            components: {
              Collapse: {
                contentBg: whiteColor,
                headerBg: whiteColor,
              },
              Button: {
                // borderRadius: 0,
                boxShadow: "none",
              },
              Input: {
                // borderRadius: 0,
                activeBorderColor: primary,
              },
            },
            token: {
              colorPrimary: primary,
              colorBorder: borderColor,
              fontFamily: font?.style?.fontFamily,
            },
          }}
        >
          <RootStyleRegistry>
            <Suspense fallback={<Loading />}>
              <Header {...{ pages }} />
              {children}
              <Footer />
            </Suspense>
          </RootStyleRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
